name: UniversalAICompanion
options:
  bundleIdPrefix: com.universalaitools
  deploymentTarget:
    iOS: "17.0"
  
targets:
  UniversalAICompanion:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - UniversalAICompanion
    resources:
      - UniversalAICompanion/Assets.xcassets
      - UniversalAICompanion/Preview Content
    settings:
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      CODE_SIGN_STYLE: Automatic
      CURRENT_PROJECT_VERSION: 1
      DEVELOPMENT_ASSET_PATHS: "\"UniversalAICompanion/Preview Content\""
      ENABLE_PREVIEWS: YES
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
      INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      LD_RUNPATH_SEARCH_PATHS: 
        - "$(inherited)"
        - "@executable_path/Frameworks"
      MARKETING_VERSION: 1.0
      PRODUCT_BUNDLE_IDENTIFIER: com.universalaitools.companion
      PRODUCT_NAME: "$(TARGET_NAME)"
      SWIFT_EMIT_LOC_STRINGS: YES
      SWIFT_VERSION: 5.0
      TARGETED_DEVICE_FAMILY: "1,2"

schemes:
  UniversalAICompanion:
    build:
      targets:
        UniversalAICompanion: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release