name: UniversalAICompanion
options:
  bundleIdPrefix: com.universalaitools
  deploymentTarget:
    iOS: "17.0"
  
targets:
  UniversalAICompanion:
    type: application
    platform: iOS
    sources:
      - path: UniversalAICompanion
    resources:
      - path: UniversalAICompanion/Assets.xcassets
      - path: UniversalAICompanion/Preview Content
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.universalaitools.companion
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ""
      ENABLE_PREVIEWS: YES
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
      INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      SWIFT_VERSION: "5.0"
      TARGETED_DEVICE_FAMILY: "1,2"
      
  UniversalAICompanionTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: UniversalAICompanionTests
    dependencies:
      - target: UniversalAICompanion
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.universalaitools.companion.tests
      
  UniversalAICompanionUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: UniversalAICompanionUITests
    dependencies:
      - target: UniversalAICompanion
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.universalaitools.companion.uitests

schemes:
  UniversalAICompanion:
    build:
      targets:
        UniversalAICompanion: all
        UniversalAICompanionTests: [test]
        UniversalAICompanionUITests: [test]
    test:
      targets:
        - UniversalAICompanionTests
        - UniversalAICompanionUITests
      gatherCoverageData: true
    run:
      config: Debug
    archive:
      config: Release
