service:
  name: "intelligent-load-balancer"
  log_level: "info"

http:
  port: "8095"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"

metrics:
  enabled: true
  path: "/metrics"

ml_model:
  learning_rate: 0.01
  training_interval: "5m"
  min_training_data: 20
  exploration_rate: 0.1

traffic_prediction:
  update_interval: "1m"
  history_retention: "7d"
  seasonal_adjustment: true

routing:
  health_threshold: 0.3
  confidence_threshold: 0.5
  max_routing_history: 1000

services:
  rust_ml_inference:
    weight: 1.0
    health_check_interval: "30s"
    timeout: "10s"
  
  go_ml_inference:
    weight: 1.0
    health_check_interval: "30s"
    timeout: "10s"
  
  rust_parameter_analytics:
    weight: 0.8
    health_check_interval: "30s"
    timeout: "5s"
  
  rust_ab_mcts:
    weight: 1.2
    health_check_interval: "30s"
    timeout: "15s"
  
  node_backend:
    weight: 1.0
    health_check_interval: "15s"
    timeout: "5s"