[package]
name = "gpu-acceleration"
version = "0.1.0"
edition = "2021"
authors = ["Universal AI Tools Team"]
description = "GPU acceleration framework for high-performance AI computations"
license = "MIT"

[lib]
name = "gpu_acceleration"
crate-type = ["cdylib", "rlib"]

[features]
default = ["cuda", "metal"]
cuda = ["cudarc"]
metal = ["metal-rs"]
opencl = ["opencl3"]
cpu-fallback = []

[dependencies]
# GPU Computing Frameworks
cudarc = { version = "0.11", optional = true, features = ["f16"] }
metal-rs = { version = "0.27", optional = true }
opencl3 = { version = "0.9", optional = true }

# Linear Algebra and Matrix Operations
nalgebra = { version = "0.32", features = ["serde"] }
ndarray = { version = "0.15", features = ["rayon", "serde"] }
rayon = "1.8"

# Async Runtime
tokio = { version = "1.35", features = ["full"] }
futures = "0.3"
async-trait = "0.1"

# Serialization for FFI
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Error Handling
thiserror = "1.0"
anyhow = "1.0"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Memory Management
bytemuck = { version = "1.14", features = ["derive"] }
memmap2 = "0.9"

# Performance Optimization
simd-adler32 = "0.3"
wide = "0.7"

# Caching
moka = { version = "0.12", features = ["future"] }

# Math utilities
num-traits = "0.2"
num-complex = "0.4"

# Random number generation
rand = "0.8"
rand_distr = "0.4"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
proptest = "1.4"

[[bench]]
name = "gpu_benchmarks"
harness = false