# Docker Compose override for development
# This file is automatically loaded by docker-compose and overrides settings in docker-compose.yml

version: '3.8'

services:
  # Override app service for development
  app:
    build:
      target: development
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - DEBUG=*
    volumes:
      # Mount source code for hot reload
      - ./src:/app/src
      - ./public:/app/public
      - ./views:/app/views
      # Exclude node_modules to use container's dependencies
      - /app/node_modules
    command: ["npm", "run", "dev"]

  # PostgreSQL with exposed port for development
  postgres:
    ports:
      - "5432:5432"

  # Redis with exposed port and no password for development
  redis:
    command: redis-server --appendonly yes --maxmemory 2gb --maxmemory-policy allkeys-lru
    environment:
      - REDIS_PASSWORD=

  # Nginx with development configuration
  nginx:
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx

  # Enable optional tools in development
  pgadmin:
    profiles: []  # Enable by default in development

  redis-commander:
    profiles: []  # Enable by default in development