version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: universal-ai-tools-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - universal-ai-network
    sysctls:
      - net.core.somaxconn=65535
    ulimits:
      memlock: -1
      nofile:
        soft: 65536
        hard: 65536

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: universal-ai-tools-redis-ui
    restart: unless-stopped
    ports:
      - '8081:8081'
    environment:
      - REDIS_HOSTS=redis:redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - universal-ai-network
    profiles:
      - dev # Only start in development

volumes:
  redis_data:
    driver: local

networks:
  universal-ai-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
