# Production Docker Compose for Universal AI Tools
version: '3.8'

services:
  # Universal AI Tools Main Service
  universal-ai-tools:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: universal-ai-tools
    restart: unless-stopped
    ports:
      - '9999:9999'
    environment:
      - NODE_ENV=production
      - PORT=9999
      - WEAVIATE_URL=${WEAVIATE_URL:-http://weaviate:8080}
      - WEAVIATE_API_KEY=${WEAVIATE_API_KEY:-}
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - DEV_API_KEY=${DEV_API_KEY}
      - REDIS_URL=redis://redis:6379
      - OLLAMA_URL=http://ollama:11434
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000,http://localhost:5173}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - PROMETHEUS_METRICS_PORT=9090
    depends_on:
      - redis
      - weaviate
      - postgres
      - ollama
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./cache:/app/cache
    networks:
      - universal-ai-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9999/api/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: athena-postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-athena}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - universal-ai-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  # Weaviate Vector Database
  weaviate:
    image: semitechnologies/weaviate:1.27.1
    container_name: athena-weaviate
    restart: unless-stopped
    ports:
      - '8090:8080'
      - '50051:50051'
    environment:
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=none
      - ENABLE_MODULES=text2vec-transformers,generative-openai,qna-openai
      - CLUSTER_HOSTNAME=node1
    volumes:
      - weaviate_data:/var/lib/weaviate
    networks:
      - universal-ai-network
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://localhost:8080/v1/.well-known/ready']
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: universal-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    networks:
      - universal-ai-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 3

  # Ollama Local LLM
  ollama:
    image: ollama/ollama:latest
    container_name: universal-ollama
    restart: unless-stopped
    ports:
      - '11434:11434'
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - universal-ai-network
    environment:
      - OLLAMA_ORIGINS=*
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:11434/api/tags']
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 120s

  # Prometheus Metrics (Optional)
  prometheus:
    image: prom/prometheus:latest
    container_name: universal-prometheus
    restart: unless-stopped
    ports:
      - '9090:9090'
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - universal-ai-network
    profiles:
      - monitoring

  # Grafana Dashboards (Optional)
  grafana:
    image: grafana/grafana:latest
    container_name: universal-grafana
    restart: unless-stopped
    ports:
      - '3001:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - universal-ai-network
    profiles:
      - monitoring

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: universal-nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - universal-ai-tools
    networks:
      - universal-ai-network
    profiles:
      - proxy

volumes:
  postgres_data:
  weaviate_data:
  redis_data:
  ollama_data:
  prometheus_data:
  grafana_data:

networks:
  universal-ai-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
