version: '3.8'

name: universal-ai-tools-mcp

services:
  # Standalone MCP Server for External LLM Access
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile.mcp-simple
    container_name: universal-ai-tools-mcp-server
    restart: unless-stopped
    ports:
      - "3456:3456"  # MCP server port
      - "3457:3457"  # WebSocket port for real-time updates
    environment:
      # Server Configuration
      - NODE_ENV=production
      - MCP_PORT=3456
      - MCP_WS_PORT=3457
      - MCP_HOST=0.0.0.0
      
      # Database Configuration
      - SUPABASE_URL=http://host.docker.internal:54321
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      
      # MCP Configuration
      - MCP_SERVER_NAME=universal-ai-tools-mcp
      - MCP_SERVER_VERSION=1.0.0
      - MCP_ENABLE_CORS=true
      - MCP_ALLOWED_ORIGINS=*
      
      # Logging
      - LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      - ./logs/mcp:/app/logs
      - ./data/mcp:/app/data
    networks:
      - ai-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3456/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: MCP Web UI for monitoring and management
  mcp-ui:
    build:
      context: .
      dockerfile: Dockerfile.mcp-ui
    container_name: universal-ai-tools-mcp-ui
    restart: unless-stopped
    ports:
      - "3458:3000"
    environment:
      - MCP_SERVER_URL=http://mcp-server:3456
      - NODE_ENV=production
    depends_on:
      - mcp-server
    networks:
      - ai-network

networks:
  ai-network:
    driver: bridge