version: '3.8'

services:
  ollama-proxy:
    image: nginx:alpine
    container_name: ollama-proxy
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/ollama-proxy.conf:/etc/nginx/conf.d/default.conf
    networks:
      - supabase_network_universal-ai-tools
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  supabase_network_universal-ai-tools:
    external: true