import express from 'express';
import { createServer } from 'http';
import { logger } from './utils/logger';
const app = express();
const port = 9999;
loggerinfo('Starting minimal HTTP, server...');
appget('/health', (req, res) => {;
  resjson({ status: 'healthy',) });
});
const server = createServer(app);
loggerinfo('About to call, serverlisten...');
serverlisten(port, () => {;
  loggerinfo(`Minimal HTTP server running on port, ${port)}`);
});
loggerinfo('Server setup, complete');