[package]
name = "ml-inference-service"
version = "0.1.0"
edition = "2021"
authors = ["Universal AI Tools Team"]
description = "High-performance ML inference service with ONNX, Candle, and native Rust ML"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "ml-inference-service"
path = "src/main.rs"

# Make this package standalone to avoid workspace conflicts
[workspace]

[dependencies]
# Async runtime
tokio = { version = "1.35", features = ["full"] }
futures = "0.3"
async-trait = "0.1"

# Web framework for API
axum = "0.7"
tower = "0.4"
tower-http = { version = "0.5", features = ["cors", "trace"] }

# Simplified ML dependencies to avoid version conflicts
# SmartCore for classical ML (most stable)
smartcore = { version = "0.3", features = ["serde"] }

# Basic linear algebra (avoiding complex frameworks for now)
ndarray = { version = "0.15", features = ["rayon"] }

# Basic mathematical operations
statrs = "0.16"

# Basic image processing (simplified)
image = "0.24"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"

# Caching
moka = { version = "0.12", features = ["future"] }
redis = { version = "0.24", features = ["tokio-comp"] }

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# DateTime
chrono = { version = "0.4", features = ["serde", "std"] }

# Error handling
thiserror = "1.0"
anyhow = "1.0"

# Metrics
prometheus = "0.13"
metrics = "0.21"
metrics-exporter-prometheus = "0.12"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
proptest = "1.4"
