version: '3.8'

services:
  searxng:
    image: searxng/searxng:latest
    container_name: universal-ai-tools-searxng
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      - SEARXNG_HOSTNAME=localhost:8080
      - SEARXNG_BASE_URL=http://localhost:8080/
      - SEARXNG_SECRET=your-secret-key-change-this
    volumes:
      - ./searxng:/etc/searxng
    networks:
      - ai-network

networks:
  ai-network:
    external: true
