server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Universal AI Tools application logs
  - job_name: universal-ai-tools
    static_configs:
      - targets:
          - localhost
        labels:
          job: universal-ai-tools
          service: api
          __path__: /var/log/universal-ai-tools/*.log

  # System logs
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/syslog

  # Docker container logs
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container_name'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'log_stream'

  # Sweet Athena specific logs
  - job_name: sweet-athena
    static_configs:
      - targets:
          - localhost
        labels:
          job: sweet-athena
          service: avatar
          __path__: /var/log/universal-ai-tools/sweet-athena*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            service: service
            trace_id: trace_id
            span_id: span_id
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - labels:
          level:
          service:
          trace_id:
          span_id: