name: UniversalAITools
options:
  minimumXcodeGenVersion: 2.38.0
  xcodeVersion: '16.0'
  deploymentTarget:
    macOS: '13.0'
  generateEmptyDirectories: true
  enableBaseInternationalization: true
packages:
  Vortex:
    url: https://github.com/twostraws/Vortex
    from: 1.0.0
  Pow:
    url: https://github.com/EmergeTools/Pow
    from: 1.0.0
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.universalai.tools
    CODE_SIGNING_ALLOWED: NO
    CODE_SIGNING_REQUIRED: NO
    CODE_SIGN_STYLE: Manual
    DEVELOPMENT_TEAM: ''
    INFOPLIST_FILE: Info.plist
    SWIFT_VERSION: 5.10
    ENABLE_HARDENED_RUNTIME: NO
    ENABLE_USER_SCRIPT_SANDBOXING: YES
    SWIFT_EMIT_LOC_STRINGS: YES
    SWIFT_STRICT_CONCURRENCY: minimal
    ENABLE_MODULE_VERIFIER: YES
    DEAD_CODE_STRIPPING: YES
    COPY_PHASE_STRIP: NO
targets:
  UniversalAITools:
    type: application
    platform: macOS
    deploymentTarget: '13.0'
    dependencies:
      - package: Vortex
      - package: Pow
    sources:
      - path: Models
      - path: Services  
      - path: Utils
      - path: Extensions
      - path: Views
        excludes:
          - Archive/**
      - path: Managers
      - path: Controllers
      - path: UniversalAIToolsApp.swift
      - path: Assets.xcassets
    excludes:
      - .derived/**
      - SourcePackages/**
      - Tests/**
    preBuildScripts:
      - name: SwiftLint
        basedOnDependencyAnalysis: false
        outputFiles:
          - $(DERIVED_FILE_DIR)/swiftlint.result
        script: |
          export PATH="$PATH:/opt/homebrew/bin"
          if which swiftlint >/dev/null; then
            swiftlint --autocorrect || true
            swiftlint
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
    settings:
      base:
        PRODUCT_NAME: Universal AI Tools
        INFOPLIST_FILE: Info.plist
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
        PRODUCT_BUNDLE_IDENTIFIER: com.universalai.tools
        DEVELOPMENT_TEAM: ''
        SWIFT_VERSION: 5.10
        ENABLE_HARDENED_RUNTIME: NO
        ENABLE_USER_SCRIPT_SANDBOXING: YES
        SWIFT_EMIT_LOC_STRINGS: YES
        SWIFT_STRICT_CONCURRENCY: minimal
        ENABLE_MODULE_VERIFIER: YES
        CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: YES
        CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
        CLANG_ENABLE_OBJC_WEAK: YES
        ENABLE_STRICT_OBJC_MSGSEND: YES
        ENABLE_TESTABILITY: YES
        GCC_NO_COMMON_BLOCKS: YES
        CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING: YES
        CLANG_WARN_COMMA: YES
        CLANG_WARN_NON_LITERAL_NULL_CONVERSION: YES
        CLANG_WARN_OBJC_LITERAL_CONVERSION: YES
        CLANG_WARN_RANGE_LOOP_ANALYSIS: YES
        CLANG_WARN_STRICT_PROTOTYPES: YES
schemes:
  UniversalAITools:
    build:
      targets:
        UniversalAITools: all
    run:
      config: Debug
    test:
      config: Debug
