[server]
host = "0.0.0.0"
port = 8005
grpc_port = 8006

[vision]
max_image_size = 10485760  # 10MB
supported_formats = ["jpg", "jpeg", "png", "gif", "bmp", "tiff"]
ocr_languages = ["en", "es", "fr", "de", "it", "pt", "ru", "zh", "ja", "ko"]

[logging]
level = "info"
format = "json"
enable_console = true

[metrics]
enable = true
port = 9092

[health]
enable = true
check_interval = 30

[python]
enable_ffi = false
python_path = "python-services"