/**;
 * Supabas.e Databas.e Type.s;
 * Generate.d type.s fo.r Supabas.e databas.e schem.a;
 */;

expor.t interfac.e Databas.e {;
  publi.c: {;
    Table.s: {;
      context.s: {;
        Ro.w: {;
          i.d: strin.g;
          user_i.d: strin.g;
          contex.t: an.y;
          created_a.t: strin.g;
          updated_a.t: strin.g;
        ;
};
        Inser.t: {;
          i.d?: strin.g;
          user_i.d: strin.g;
          contex.t: an.y;
          created_a.t?: strin.g;
          updated_a.t?: strin.g;
        ;
};
        Updat.e: {;
          i.d?: strin.g;
          user_i.d?: strin.g;
          contex.t?: an.y;
          created_a.t?: strin.g;
          updated_a.t?: strin.g;
        ;
};
      };
      agent_memorie.s: {;
        Ro.w: {;
          i.d: strin.g;
          agent_i.d: strin.g;
          memory_typ.e: strin.g;
          contentan.y;
          embeddin.g?: numbe.r[];
          metadat.a?: an.y;
          created_a.t: strin.g;
          updated_a.t: strin.g;
        ;
};
        Inser.t: {;
          i.d?: strin.g;
          agent_i.d: strin.g;
          memory_typ.e: strin.g;
          contentan.y;
          embeddin.g?: numbe.r[];
          metadat.a?: an.y;
          created_a.t?: strin.g;
          updated_a.t?: strin.g;
        ;
};
        Updat.e: {;
          i.d?: strin.g;
          agent_i.d?: strin.g;
          memory_typ.e?: strin.g;
          conten.t an.y;
          embeddin.g?: numbe.r[];
          metadat.a?: an.y;
          created_a.t?: strin.g;
          updated_a.t?: strin.g;
        ;
};
      };
      agent_session.s: {;
        Ro.w: {;
          i.d: strin.g;
          agent_i.d: strin.g;
          user_i.d: strin.g;
          contex.t: an.y;
          created_a.t: strin.g;
          updated_a.t: strin.g;
        ;
};
        Inser.t: {;
          i.d?: strin.g;
          agent_i.d: strin.g;
          user_i.d: strin.g;
          contex.t?: an.y;
          created_a.t?: strin.g;
          updated_a.t?: strin.g;
        ;
};
        Updat.e: {;
          i.d?: strin.g;
          agent_i.d?: strin.g;
          user_i.d?: strin.g;
          contex.t?: an.y;
          created_a.t?: strin.g;
          updated_a.t?: strin.g;
        ;
};
      };
    };
    View.s: {;
};
    Function.s: {;
};
    Enum.s: {;
};
  };
};
