name: Feature Request
description: Suggest an idea for Universal AI Tools
title: '[Feature]: '
labels: ['enhancement', 'triage']
assignees:
  - christianmerrill

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: Alternatively, we could...
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Which component would this feature affect?
      multiple: true
      options:
        - Backend API
        - Frontend UI
        - Database/Supabase
        - Authentication
        - AI Agents
        - DSPy Orchestration
        - Memory System
        - Sweet Athena
        - Performance
        - Security
        - Docker/Deployment
        - Documentation
        - CLI Tools
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would significantly improve my workflow
        - High - Essential for my use case
        - Critical - Blocking my ability to use the system
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Implementation Complexity (if known)
      description: If you have technical knowledge, how complex do you think this would be?
      options:
        - Simple - Minor changes, quick implementation
        - Medium - Moderate changes, some new functionality
        - Complex - Major changes, significant new functionality
        - Very Complex - Architectural changes, extensive work
        - Unknown - I'm not sure about the technical complexity
    validations:
      required: false

  - type: textarea
    id: use-case
    attributes:
      label: Use Case Details
      description: Please describe your specific use case and how this feature would help you
      placeholder: |
        I am trying to...
        This would help me because...
        Currently I have to...
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What would need to be true for this feature to be considered complete?
      placeholder: |
        - [ ] Feature does X
        - [ ] Feature handles Y edge case
        - [ ] Feature includes documentation
        - [ ] Feature includes tests
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If applicable, add mockups, wireframes, or examples from other tools that demonstrate what you're looking for.

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Interest
      description: Are you interested in helping implement this feature?
      options:
        - label: I would be interested in contributing to the implementation
        - label: I can provide testing and feedback during development
        - label: I can help with documentation for this feature

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues and feature requests to ensure this hasn't been suggested before
          required: true
        - label: I have provided a clear description of the feature and its benefits
          required: true
        - label: I understand this is an open-source project and feature requests may take time to implement
          required: true
