name: 🔒 Security Vulnerability
description: Report a security vulnerability (private security issues should be reported via security@universal-ai-tools.com)
title: '[SECURITY] '
labels: ['security', 'vulnerability', 'urgent']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 🔒 Security Vulnerability Report

        **⚠️ IMPORTANT SECURITY NOTICE ⚠️**

        If this is a **critical security vulnerability** that could be exploited, please:
        1. **DO NOT** create a public issue
        2. Email us privately at: security@universal-ai-tools.com
        3. Include all details below in your private report

        For non-critical security improvements or questions, you can continue with this public issue.

  - type: dropdown
    id: vulnerability-type
    attributes:
      label: Vulnerability Type
      description: What type of security issue is this?
      options:
        - Authentication/Authorization bypass
        - Cross-Site Scripting (XSS)
        - SQL Injection
        - Remote Code Execution (RCE)
        - Information Disclosure
        - Cross-Site Request Forgery (CSRF)
        - Insecure Direct Object Reference
        - Security Misconfiguration
        - Insecure Cryptographic Storage
        - Insufficient Transport Layer Security
        - Dependency Vulnerability
        - Electron Security Issue
        - API Security Issue
        - Other (specify in description)
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this security issue?
      options:
        - Critical - Immediate threat, full system compromise possible
        - High - Significant security risk, sensitive data exposure
        - Medium - Moderate security risk, limited impact
        - Low - Minor security improvement, best practice
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which part of the system is affected?
      options:
        - Electron Frontend (Authentication, XSS, CSP)
        - API Gateway (Go Service)
        - Rust Services (LLM Router, ML Inference)
        - Database/Supabase Integration
        - TypeScript Backend (Legacy)
        - Build/Deployment Pipeline
        - Dependencies/Third-party Libraries
        - Configuration Files
        - Documentation/Examples
    validations:
      required: true

  - type: textarea
    id: vulnerability-description
    attributes:
      label: Vulnerability Description
      description: Detailed description of the security issue
      placeholder: |
        Provide a clear description of:
        - What the vulnerability is
        - How it could be exploited
        - What data or systems are at risk
        - Any preconditions needed for exploitation
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the security issue
      placeholder: |
        1. Navigate to the login page
        2. Enter malicious payload in username field: <script>alert('XSS')</script>
        3. Submit the form
        4. Observe script execution in browser

        **Note:** Please use safe, non-destructive payloads for demonstration
    validations:
      required: true

  - type: textarea
    id: impact-assessment
    attributes:
      label: Impact Assessment
      description: What is the potential impact if this vulnerability is exploited?
      placeholder: |
        - Could an attacker access sensitive user data?
        - Could an attacker gain unauthorized system access?
        - Could an attacker disrupt service availability?
        - What is the blast radius of this vulnerability?
    validations:
      required: true

  - type: textarea
    id: affected-versions
    attributes:
      label: Affected Versions
      description: Which versions of the application are affected?
      placeholder: |
        - Current main branch (specify commit hash if possible)
        - Version 1.2.3 through 1.5.0
        - All versions since feature X was introduced
    validations:
      required: true

  - type: textarea
    id: mitigation-suggestions
    attributes:
      label: Suggested Mitigation
      description: If you have suggestions for fixing this vulnerability, please share them
      placeholder: |
        - Input validation and sanitization
        - Implement proper authentication checks
        - Use parameterized queries
        - Add Content Security Policy headers
        - Update vulnerable dependency to version X.Y.Z

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: |
        - References to similar vulnerabilities (CVE numbers, etc.)
        - Tools or methods used to discover this issue
        - Screenshots or proof-of-concept (if safe to share)
        - Related security issues or dependencies

  - type: checkboxes
    id: verification
    attributes:
      label: Security Checklist
      description: Please confirm the following
      options:
        - label: I have verified this is a legitimate security concern
        - label: I have tested this in a safe, isolated environment
        - label: I understand the responsible disclosure process
        - label: I have not shared details of this vulnerability publicly elsewhere
        - label: I confirm this is not a critical vulnerability requiring private disclosure

  - type: markdown
    attributes:
      value: |
        ## 🛡️ Security Response Process

        1. **Acknowledgment**: We'll acknowledge receipt within 24 hours
        2. **Triage**: Our security team will assess the issue within 48 hours  
        3. **Investigation**: We'll investigate and develop a fix
        4. **Resolution**: We'll deploy the fix and notify you when resolved
        5. **Recognition**: We'll credit you in our security acknowledgments (if desired)

        Thank you for helping keep Universal AI Tools secure! 🙏
