[server]
host = "0.0.0.0"
port = 8003
grpc_port = 8004

[dspy]
max_agents = 10
orchestration_timeout = 30
reasoning_depth = 5

[logging]
level = "info"
format = "json"
enable_console = true

[metrics]
enable = true
port = 9091

[health]
enable = true
check_interval = 30

[python]
enable_ffi = false
python_path = "python-services"