version: '3.8'

# Monitoring Stack for Universal AI Tools
# Includes Prometheus, Grafana, and distributed tracing

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: uat-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./distributed-tracing/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    networks:
      - uat-monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: uat-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=redis-datasource
    volumes:
      - grafana-data:/var/lib/grafana
      - ./distributed-tracing/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - uat-monitoring

  tempo:
    image: grafana/tempo:latest
    container_name: uat-tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./distributed-tracing/tempo.yaml:/etc/tempo.yaml
      - tempo-data:/tmp/tempo
    ports:
      - "3200:3200"   # tempo
      - "4317:4317"   # otlp grpc
      - "4318:4318"   # otlp http
    networks:
      - uat-monitoring

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: uat-otel-collector
    command: [ "--config=/etc/otel-collector-config.yml" ]
    volumes:
      - ./distributed-tracing/otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "55679:55679" # zpages extension
    depends_on:
      - tempo
      - prometheus
    networks:
      - uat-monitoring

networks:
  uat-monitoring:
    driver: bridge

volumes:
  prometheus-data:
  grafana-data:
  tempo-data: