[server]
host = "0.0.0.0"
port = 8001
grpc_port = 8002

[mlx]
model_path = "/models"
device = "auto"
max_tokens = 2048
temperature = 0.7
top_p = 0.9

[logging]
level = "info"
format = "json"
enable_console = true

[metrics]
enable = true
port = 9090

[health]
enable = true
check_interval = 30

[python]
enable_ffi = false
python_path = "python-services"