# Staging Environment Configuration
name: staging

# Environment protection rules
protection_rules:
  required_reviewers: 1
  prevent_self_review: false
  dismiss_stale_reviews: true
  require_code_owner_reviews: false

# Environment variables (non-sensitive)
variables:
  DEPLOYMENT_ENV: staging
  API_BASE_URL: https://api-staging.universal-ai-tools.com
  WEBSOCKET_URL: wss://ws-staging.universal-ai-tools.com
  MONITORING_URL: https://monitoring-staging.universal-ai-tools.com
  
  # Resource limits for staging
  POSTGRES_MAX_CONNECTIONS: "100"
  REDIS_MAX_MEMORY: "256mb"
  API_GATEWAY_WORKERS: "2"
  LLM_ROUTER_WORKERS: "2"
  
  # Feature flags
  ENABLE_DEBUG_LOGGING: "true"
  ENABLE_PERFORMANCE_TRACING: "true"
  ENABLE_EXPERIMENTAL_FEATURES: "true"
  
  # Rate limiting (more permissive for testing)
  RATE_LIMIT_REQUESTS_PER_MINUTE: "1000"
  RATE_LIMIT_BURST_SIZE: "100"

# Secrets (configured in GitHub UI)
# - STAGING_POSTGRES_PASSWORD
# - STAGING_NEO4J_PASSWORD  
# - STAGING_GRAFANA_PASSWORD
# - STAGING_JWT_SECRET
# - STAGING_ENCRYPTION_KEY