[package]
name = "api-gateway"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "api-gateway"
path = "src/main.rs"

[dependencies]
# Web Framework
axum = { version = "0.7", features = ["multipart", "ws"] }
tower = { version = "0.4", features = ["util", "timeout", "limit", "load-shed", "balance"] }
tower-http = { version = "0.5", features = ["fs", "trace", "cors", "timeout"] }
hyper = { version = "1.0", features = ["full"] }
tokio = { version = "1.0", features = ["full"] }

# HTTP Client for Service Communication  
reqwest = { version = "0.12", features = ["json", "stream"] }

# Serialization & JSON
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"

# Async & Concurrency
futures = "0.3"
async-trait = "0.1"
dashmap = "5.0"

# Configuration
config = "0.14"
toml = "0.8"
clap = { version = "4.0", features = ["derive"] }

# Logging & Tracing
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }

# Error Handling
anyhow = "1.0"
thiserror = "2.0"

# Time & UUID
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v4", "serde"] }

# Load Balancing & Service Discovery
consul = "0.4"

# Health Checks & Monitoring
prometheus = "0.13"

# Rate Limiting
rand = "0.8"

# System Integration
sys-info = "0.9"

# Pattern Matching for Log Analysis
regex = "1.0"

# Code Analysis Dependencies for ProactiveCodeAnalyzer
walkdir = "2.4"

[dev-dependencies]
tokio-test = "0.4"
wiremock = "0.5"