version: '3.8'

services:
  ab-mcts-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ab-mcts-rust-service
    environment:
      - RUST_LOG=info
      - MCTS_CONFIG_PATH=/app/config
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./config:/app/config:ro
      - mcts_data:/app/data
    networks:
      - universal-ai-network
    depends_on:
      - redis
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1.0"
        reservations:
          memory: 256M
          cpus: "0.5"
    healthcheck:
      test: ["CMD", "echo", "health check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: mcts-redis
    command: redis-server --appendonly yes --maxmemory 128mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    networks:
      - universal-ai-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: "0.5"

volumes:
  mcts_data:
    driver: local
  redis_data:
    driver: local

networks:
  universal-ai-network:
    external: true