# Production configuration for Parameter Analytics Service
# Optimized for high-performance production deployment

[service]
name = "parameter-analytics-service"
version = "0.1.0"
environment = "production"

[analytics]
# Buffer configuration for batch processing
buffer_size = 2000
flush_interval_ms = 15000  # 15 seconds for production
cache_expiry_ms = 600000   # 10 minutes

# Processing configuration
parallel_workers = 16      # Adjust based on CPU cores
enable_ml_insights = true
min_sample_size = 25       # Higher threshold for production

# Performance tuning
enable_statistics = true
enable_trend_analysis = true
enable_optimization = true

[cache]
# Redis configuration
redis_url = "redis://localhost:6379"
redis_pool_size = 20
redis_timeout_ms = 5000
redis_retry_attempts = 3

# Cache TTL settings (seconds)
effectiveness_ttl = 300    # 5 minutes
insights_ttl = 600        # 10 minutes
analytics_ttl = 60        # 1 minute
execution_ttl = 3600      # 1 hour

[database]
# Optional database configuration
# database_url = "postgresql://user:pass@localhost:5432/analytics"
enable_persistence = false
connection_pool_size = 10
query_timeout_ms = 10000

[logging]
level = "info"
format = "json"
enable_file_logging = true
log_file_path = "/app/logs/analytics.log"
max_file_size_mb = 100
max_files = 10

[monitoring]
enable_metrics = true
metrics_port = 9090
enable_health_checks = true
health_check_interval_ms = 30000

# Performance monitoring
enable_performance_tracking = true
slow_operation_threshold_ms = 1000
enable_circuit_breaker = true

[security]
# Security configuration
enable_rate_limiting = true
max_requests_per_minute = 1000
max_batch_size = 500

# Validation settings
max_input_size_bytes = 1048576  # 1MB
enable_input_sanitization = true

[resources]
# Resource limits
max_memory_mb = 2048
max_cpu_percent = 80
max_cache_size_mb = 512

# Queue limits
max_queue_size = 10000
queue_timeout_ms = 30000

[optimization]
# ML optimization settings
enable_auto_tuning = true
optimization_interval_ms = 300000  # 5 minutes
learning_rate = 0.01
confidence_threshold = 0.7

# Feature flags
enable_advanced_analytics = true
enable_predictive_insights = true
enable_anomaly_detection = true