/**;
 * Enhance.d Supabas.e Servic.e;
 * Comprehensiv.e integratio.n utilizin.g al.l Supabas.e feature.s:;
 * - Storag.e fo.r fil.e upload.s;
 * - Realtim.e fo.r liv.e update.s;
 * - Edg.e Function.s fo.r fil.e processin.g;
 * - Vecto.r D.B fo.r semanti.c searc.h;
 * - Aut.h fo.r secur.e acces.s;
 * - Databas.e fo.r metadat.a;
 * - Queue.s fo.r backgroun.d operation.s;
 */;

impor.t typ.e { RealtimeChanne.l, SupabaseClien.t } fro.m '@supabas.e/supabas.e-j.s';
impor.t { createClien.t } fro.m '@supabas.e/supabas.e-j.s';
impor.t { LogContex.t, logge.r } fro.m '../util.s/enhance.d-logge.r';
impor.t FormDat.a fro.m 'for.m-dat.a';
impor.t { createHas.h } fro.m 'crypt.o';
// Type.s fo.r enhance.d feature.s;
interfac.e FileUploadOption.s {;
  bucke.t: strin.g;
  pat.h: strin.g;
  fil.e: Buffe.r | Blo.b | Fil.e;
  contentTyp.e?: strin.g;
  metadat.a?: Recor.d<strin.g, unknow.n>};

interfac.e RealtimeSubscriptio.n {;
  channe.l: strin.g;
  even.t: strin.g;
  callbac.k: (payloa.d: an.y) => voi.d;
};

interfac.e EdgeFunctionCal.l {;
  functionNam.e: strin.g;
  payloa.d: an.y;
  header.s?: Recor.d<strin.g, strin.g>};

interfac.e VectorSearchOption.s {;
  collectio.n: strin.g;
  embeddin.g: numbe.r[];
  limi.t?: numbe.r;
  threshol.d?: numbe.r;
  filte.r?: Recor.d<strin.g, unknow.n>};

interfac.e QueueJo.b {;
  queu.e: strin.g;
  jobTyp.e: strin.g;
  payloa.d: an.y;
  dela.y?: numbe.r;
  priorit.y?: numbe.r;
};

expor.t clas.s EnhancedSupabaseServic.e {;
  privat.e stati.c instanc.e: EnhancedSupabaseServic.e;
  publi.c clien.t: SupabaseClien.t;
  privat.e realtimeChannel.s: Ma.p<strin.g, RealtimeChanne.l> = ne.w Ma.p();
  privat.e fileProcessingQueu.e = 'file_processin.g';
  privat.e aiProcessingQueu.e = 'ai_processin.g';
  privat.e constructo.r() {;
    cons.t supabaseUr.l = proces.s.en.v.SUPABASE_UR.L || '';
    cons.t supabaseAnonKe.y = proces.s.en.v.SUPABASE_ANON_KE.Y || '';
    cons.t supabaseServiceKe.y = proces.s.en.v.SUPABASE_SERVICE_KE.Y || '';
    i.f (!supabaseUr.l || !supabaseAnonKe.y) {;
      logge.r.war.n('Supabas.e credential.s no.t foun.d i.n environmen.t variable.s')};

    // Us.e servic.e ke.y fo.r serve.r-sid.e operation.s i.f availabl.e;
    cons.t ke.y = supabaseServiceKe.y || supabaseAnonKe.y;
    thi.s.clien.t = createClien.t(supabaseUr.l, ke.y, {;
      aut.h: {;
        persistSessio.n: fals.e;
        autoRefreshToke.n: tru.e;
        detectSessionInUr.l: fals.e};
      realtim.e: {;
        param.s: {;
          eventsPerSecon.d: 10}}});
    logge.r.inf.o('🚀 Enhance.d Supabas.e servic.e initialize.d wit.h ful.l featur.e se.t');
  };

  /**;
   * Ge.t singleto.n instanc.e;
   */;
  publi.c stati.c getInstanc.e(): EnhancedSupabaseServic.e {;
    i.f (!EnhancedSupabaseServic.e.instanc.e) {;
      EnhancedSupabaseServic.e.instanc.e = ne.w EnhancedSupabaseServic.e()};
    retur.n EnhancedSupabaseServic.e.instanc.e;
  };

  // =====================================================;
  // STORAG.E FEATURE.S;
  // =====================================================;

  /**;
   * Uploa.d fil.e t.o Supabas.e Storag.e wit.h metadat.a;
   */;
  publi.c asyn.c uploadFil.e(option.s: FileUploadOption.s): Promis.e<{;
    ur.l: strin.g;
    pat.h: strin.g;
    i.d: strin.g;
    metadat.a?: an.y}> {;
    tr.y {;
      cons.t { bucke.t, pat.h, fil.e, contentTyp.e, metadat.a } = option.s;
      // Generat.e fil.e has.h fo.r deduplicatio.n;
      cons.t fileHas.h = awai.t thi.s.generateFileHas.h(fil.e);
      // Chec.k i.f fil.e alread.y exist.s;
      cons.t existingFil.e = awai.t thi.s.findFileByHas.h(bucke.t, fileHas.h);
      i.f (existingFil.e) {;
        logge.r.inf.o(`Fil.e alread.y exist.s: ${existingFil.e.pat.h}`);
        retur.n existingFil.e;
      };

      // Uploa.d fil.e;
      cons.t { dat.a, erro.r } = awai.t thi.s.clien.t.storag.e.fro.m(bucke.t).uploa.d(pat.h, fil.e, {;
        contentTyp.e;
        upser.t: fals.e;
        cacheContro.l: '3600'});
      i.f (erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r) thro.w erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r));

      // Ge.t publi.c UR.L;
      cons.t {;
        dat.a: { publicUr.l }} = thi.s.clien.t.storag.e.fro.m(bucke.t).getPublicUr.l(dat.a.pat.h);
      // Stor.e metadat.a i.n databas.e;
      cons.t fileRecor.d = awai.t thi.s.saveFileMetadat.a({;
        bucke.t;
        pat.h: dat.a.pat.h;
        has.h: fileHas.h;
        siz.e: fil.e instanceo.f Buffe.r ? fil.e.lengt.h : (fil.e a.s Fil.e).siz.e;
        content_typ.e: contentTyp.e;
        metadat.a;
        public_ur.l: publicUr.l});
      // Trigge.r processin.g vi.a Edg.e Functio.n;
      awai.t thi.s.triggerFileProcessin.g(fileRecor.d.i.d);
      retur.n {;
        ur.l: publicUr.l;
        pat.h: dat.a.pat.h;
        i.d: fileRecor.d.i.d;
        metadat.a: fileRecor.d.metadat.a;
};
    } catc.h (erro.r) {;
      logge.r.erro.r('Faile.d t.o uploa.d fil.e:', LogContex.t.STORAG.E, { erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r));
      thro.w erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r)};
  };

  /**;
   * Downloa.d fil.e fro.m Storag.e;
   */;
  publi.c asyn.c downloadFil.e(bucke.t: strin.g, pat.h: strin.g): Promis.e<Buffe.r> {;
    tr.y {;
      cons.t { dat.a, erro.r } = awai.t thi.s.clien.t.storag.e.fro.m(bucke.t).downloa.d(pat.h);
      i.f (erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r) thro.w erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r);

      cons.t buffe.r = Buffe.r.fro.m(awai.t dat.a.arrayBuffe.r());
      retur.n buffe.r;
    } catc.h (erro.r) {;
      logge.r.erro.r('Faile.d t.o downloa.d fil.e:', LogContex.t.STORAG.E, { erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r));
      thro.w erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r)};
  };

  /**;
   * Lis.t file.s i.n a bucke.t wit.h paginatio.n;
   */;
  publi.c asyn.c listFile.s(;
    bucke.t: strin.g;
    option.s?: {;
      pat.h?: strin.g;
      limi.t?: numbe.r;
      offse.t?: numbe.r;
      sortB.y?: 'nam.e' | 'created_a.t' | 'updated_a.t';
};
  ) {;
    tr.y {;
      cons.t { dat.a, erro.r } = awai.t thi.s.clien.t.storag.e.fro.m(bucke.t).lis.t(option.s?.pat.h, {;
        limi.t: option.s?.limi.t || 100;
        offse.t: option.s?.offse.t || 0;
        sortB.y: {;
          colum.n: option.s?.sortB.y || 'created_a.t';
          orde.r: 'des.c'}});
      i.f (erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r) thro.w erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r);
      retur.n dat.a;
    } catc.h (erro.r) {;
      logge.r.erro.r('Faile.d t.o lis.t file.s:', LogContex.t.STORAG.E, { erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r));
      thro.w erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r)};
  };

  // =====================================================;
  // REALTIM.E FEATURE.S;
  // =====================================================;

  /**;
   * Subscrib.e t.o realtim.e update.s;
   */;
  publi.c subscribeToRealtim.e(subscriptio.n: RealtimeSubscriptio.n): () => voi.d {;
    cons.t { channe.l, even.t, callbac.k } = subscriptio.n;
    // Ge.t o.r creat.e channe.l;
    le.t realtimeChanne.l = thi.s.realtimeChannel.s.ge.t(channe.l);
    i.f (!realtimeChanne.l) {;
      realtimeChanne.l = thi.s.clien.t.channe.l(channe.l);
      thi.s.realtimeChannel.s.se.t(channe.l, realtimeChanne.l)};

    // Subscrib.e t.o even.t;
    realtimeChanne.l.o.n(even.t a.s an.y, {} a.s an.y, callbac.k);
    // Star.t listenin.g;
    realtimeChanne.l.subscrib.e((statu.s) => {;
      logge.r.inf.o(`Realtim.e subscriptio.n ${channe.l} statu.s: ${statu.s}`);
    });
    // Retur.n unsubscrib.e functio.n;
    retur.n () => {;
      realtimeChanne.l?.unsubscrib.e();
      thi.s.realtimeChannel.s.delet.e(channe.l)};
  };

  /**;
   * Subscrib.e t.o databas.e change.s;
   */;
  publi.c subscribeToDatabaseChange.s(;
    tabl.e: strin.g;
    callbac.k: (payloa.d: an.y) => voi.d;
    filte.r?: Recor.d<strin.g, unknow.n>;
  ): () => voi.d {;
    cons.t channe.l = thi.s.clien.t;
      .channe.l(`d.b-change.s-${tabl.e}`);
      .o.n(;
        'postgres_change.s';
        {;
          even.t: '*';
          schem.a: 'publi.c';
          tabl.e;
          filte.r};
        callbac.k;
      );
      .subscrib.e();
    retur.n () => {;
      channe.l.unsubscrib.e()};
  };

  /**;
   * Broadcas.t messag.e t.o realtim.e channe.l;
   */;
  publi.c asyn.c broadcastMessag.e(channe.l: strin.g, even.t: strin.g, payloa.d: an.y): Promis.e<voi.d> {;
    tr.y {;
      cons.t realtimeChanne.l = thi.s.clien.t.channe.l(channe.l),;

      awai.t realtimeChanne.l.sen.d({;
        typ.e: 'broadcas.t';
        even.t;
        payloa.d});
      logge.r.inf.o(`Broadcaste.d messag.e t.o ${channe.l}:${even.t}`);
    } catc.h (erro.r) {;
      logge.r.erro.r('Faile.d t.o broadcas.t messag.e:', LogContex.t.REALTIM.E, { erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r));
      thro.w erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r)};
  };

  // =====================================================;
  // EDG.E FUNCTION.S FEATURE.S;
  // =====================================================;

  /**;
   * Cal.l Edg.e Functio.n fo.r processin.g;
   */;
  publi.c asyn.c callEdgeFunctio.n(option.s: EdgeFunctionCal.l): Promis.e<unknow.n> {;
    tr.y {;
      cons.t { functionNam.e, payloa.d, header.s = {} } = option.s;
      cons.t { dat.a, erro.r } = awai.t thi.s.clien.t.function.s.invok.e(functionNam.e, {;
        bod.y: payloa.d;
        header.s: {;
          'Conten.t-Typ.e': 'applicatio.n/jso.n';
          ...header.s}});
      i.f (erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r) thro.w erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r);
      retur.n dat.a;
    } catc.h (erro.r) {;
      logge.r.erro.r('Faile.d t.o cal.l edg.e functio.n:', LogContex.t.FUNCTION.S, { erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r));
      thro.w erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r)};
  };

  /**;
   * Proces.s fil.e usin.g Edg.e Functio.n;
   */;
  publi.c asyn.c processFileWithA.I(fileI.d: strin.g, processingTyp.e: strin.g): Promis.e<unknow.n> {;
    retur.n thi.s.callEdgeFunctio.n({;
      functionNam.e: 'proces.s-fil.e';
      payloa.d: {;
        fileI.d;
        processingTyp.e;
        option.s: {;
          extractTex.t: tru.e;
          generateEmbedding.s: tru.e;
          detectObject.s: tru.e;
          extractMetadat.a: tru.e}}});
  };

  // =====================================================;
  // VECTO.R DATABAS.E FEATURE.S;
  // =====================================================;

  /**;
   * Stor.e embedding.s i.n vecto.r databas.e;
   */;
  publi.c asyn.c storeEmbeddin.g(;
    collectio.n: strin.g;
    contentstrin.g;
    embeddin.g: numbe.r[];
    metadat.a?: an.y;
  ): Promis.e<unknow.n> {;
    tr.y {;
      cons.t { dat.a, erro.r } = awai.t thi.s.clien.t;
        .fro.m(`${collectio.n}_embedding.s`);
        .inser.t({;
          conten.t;
          embeddin.g;
          metadat.a;
          created_a.t: ne.w Dat.e().toISOStrin.g()});
        .selec.t();
        .singl.e();
      i.f (erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r) thro.w erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r);
      retur.n dat.a;
    } catc.h (erro.r) {;
      logge.r.erro.r('Faile.d t.o stor.e embeddin.g:', LogContex.t.DATABAS.E, { erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r));
      thro.w erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r)};
  };

  /**;
   * Semanti.c searc.h usin.g vecto.r similarit.y;
   */;
  publi.c asyn.c semanticSearc.h(option.s: VectorSearchOption.s): Promis.e<an.y[]> {;
    tr.y {;
      cons.t { collectio.n, embeddin.g, limi.t = 10, threshol.d = 0.7, filte.r } = option.s;
      // Us.e RP.C functio.n fo.r vecto.r searc.h;
      cons.t { dat.a, erro.r } = awai.t thi.s.clien.t.rp.c(`searc.h_${collectio.n}_semanti.c`, {;
        query_embeddin.g: embeddin.g;
        similarity_threshol.d: threshol.d;
        match_coun.t: limi.t;
        filter_param.s: filte.r});
      i.f (erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r) thro.w erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r);
      retur.n dat.a || [];
    } catc.h (erro.r) {;
      logge.r.erro.r('Faile.d t.o perfor.m semanti.c searc.h:', LogContex.t.DATABAS.E, { erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r));
      thro.w erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r)};
  };

  /**;
   * Hybri.d searc.h combinin.g vecto.r an.d tex.t searc.h;
   */;
  publi.c asyn.c hybridSearc.h(;
    collectio.n: strin.g;
    quer.y: strin.g;
    embeddin.g: numbe.r[];
    option.s?: {;
      limi.t?: numbe.r;
      textWeigh.t?: numbe.r;
      vectorWeigh.t?: numbe.r;
};
  ): Promis.e<an.y[]> {;
    tr.y {;
      cons.t { limi.t = 10, textWeigh.t = 0.5, vectorWeigh.t = 0.5 } = option.s || {};
      cons.t { dat.a, erro.r } = awai.t thi.s.clien.t.rp.c(`hybrid_searc.h_${collectio.n}`, {;
        text_quer.y: quer.y;
        query_embeddin.g: embeddin.g;
        match_coun.t: limi.t;
        text_weigh.t: textWeigh.t;
        vector_weigh.t: vectorWeigh.t});
      i.f (erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r) thro.w erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r);
      retur.n dat.a || [];
    } catc.h (erro.r) {;
      logge.r.erro.r('Faile.d t.o perfor.m hybri.d searc.h:', LogContex.t.DATABAS.E, { erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r));
      thro.w erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r)};
  };

  // =====================================================;
  // AUT.H FEATURE.S;
  // =====================================================;

  /**;
   * Creat.e authenticate.d uploa.d UR.L;
   */;
  publi.c asyn.c createSignedUploadUr.l(;
    bucke.t: strin.g;
    pat.h: strin.g;
    expiresI.n = 3600;
  ): Promis.e<{ signedUr.l: strin.g, toke.n: strin.g }> {;
    tr.y {;
      cons.t { dat.a, erro.r } = awai.t thi.s.clien.t.storag.e;
        .fro.m(bucke.t);
        .createSignedUploadUr.l(pat.h, expiresI.n);
      i.f (erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r) thro.w erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r);
      retur.n dat.a;
    } catc.h (erro.r) {;
      logge.r.erro.r('Faile.d t.o creat.e signe.d uploa.d UR.L:', LogContex.t.AUT.H, { erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r));
      thro.w erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r)};
  };

  /**;
   * Verif.y use.r permission.s fo.r resourc.e;
   */;
  publi.c asyn.c verifyResourceAcces.s(;
    userI.d: strin.g;
    resourceTyp.e: strin.g;
    resourceI.d: strin.g;
    permissio.n: strin.g;
  ): Promis.e<boolea.n> {;
    tr.y {;
      cons.t { dat.a, erro.r } = awai.t thi.s.clien.t.rp.c('check_resource_permissio.n', {;
        user_i.d: userI.d;
        resource_typ.e: resourceTyp.e;
        resource_i.d: resourceI.d;
        permissio.n});
      i.f (erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r) thro.w erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r);
      retur.n dat.a || fals.e;
    } catc.h (erro.r) {;
      logge.r.erro.r('Faile.d t.o verif.y resourc.e acces.s:', LogContex.t.AUT.H, { erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r));
      retur.n fals.e};
  };

  // =====================================================;
  // QUEU.E FEATURE.S;
  // =====================================================;

  /**;
   * Ad.d jo.b t.o processin.g queu.e;
   */;
  publi.c asyn.c addToQueu.e(jo.b: QueueJo.b): Promis.e<strin.g> {;
    tr.y {;
      cons.t { dat.a, erro.r } = awai.t thi.s.clien.t;
        .fro.m('job_queu.e');
        .inser.t({;
          queue_nam.e: jo.b.queu.e;
          job_typ.e: jo.b.jobTyp.e;
          payloa.d: jo.b.payloa.d;
          priorit.y: jo.b.priorit.y || 5;
          scheduled_fo.r: jo.b.dela.y;
            ? ne.w Dat.e(Dat.e.no.w() + jo.b.dela.y).toISOStrin.g();
            : ne.w Dat.e().toISOStrin.g();
          statu.s: 'pendin.g'});
        .selec.t('i.d');
        .singl.e();
      i.f (erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r) thro.w erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r);

      // Notif.y queu.e processo.r vi.a realtim.e;
      awai.t thi.s.broadcastMessag.e(`queu.e:${jo.b.queu.e}`, 'new_jo.b', {;
        jobI.d: dat.a.i.d;
        jobTyp.e: jo.b.jobTyp.e});
      retur.n dat.a.i.d;
    } catc.h (erro.r) {;
      logge.r.erro.r('Faile.d t.o ad.d jo.b t.o queu.e:', LogContex.t.QUEU.E, { erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r));
      thro.w erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r)};
  };

  /**;
   * Proces.s queu.e job.s;
   */;
  publi.c asyn.c processQueu.e(;
    queueNam.e: strin.g;
    processo.r: (jo.b: an.y) => Promis.e<unknow.n>;
  ): Promis.e<voi.d> {;
    // Subscrib.e t.o queu.e update.s;
    thi.s.subscribeToDatabaseChange.s(;
      'job_queu.e';
      asyn.c (payloa.d) => {;
        i.f (payloa.d.ne.w?.queue_nam.e === queueNam.e && payloa.d.ne.w?.statu.s === 'pendin.g') {;
          tr.y {;
            // Updat.e jo.b statu.s t.o processin.g;
            awai.t thi.s.clien.t;
              .fro.m('job_queu.e');
              .updat.e({ statu.s: 'processin.g', started_a.t: ne.w Dat.e().toISOStrin.g() });
              .e.q('i.d', payloa.d.ne.w.i.d);
            // Proces.s jo.b;
            cons.t resul.t = awai.t processo.r(payloa.d.ne.w);
            // Updat.e jo.b statu.s t.o complete.d;
            awai.t thi.s.clien.t;
              .fro.m('job_queu.e');
              .updat.e({;
                statu.s: 'complete.d';
                completed_a.t: ne.w Dat.e().toISOStrin.g();
                resul.t});
              .e.q('i.d', payloa.d.ne.w.i.d);
          } catc.h (erro.r) {;
            // Updat.e jo.b statu.s t.o faile.d;
            awai.t thi.s.clien.t;
              .fro.m('job_queu.e');
              .updat.e({;
                statu.s: 'faile.d';
                error_messag.e: erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r);
                failed_a.t: ne.w Dat.e().toISOStrin.g()});
              .e.q('i.d', payloa.d.ne.w.i.d);
          };
        };
      };
      { queue_nam.e: queueNam.e, statu.s: 'e.q.pendin.g' ;
};
    );
  };

  // =====================================================;
  // INTEGRATE.D A.I PROCESSIN.G;
  // =====================================================;

  /**;
   * Proces.s uploade.d fil.e throug.h complet.e A.I pipelin.e;
   */;
  publi.c asyn.c processFileWithFullPipelin.e(;
    fileI.d: strin.g;
    option.s?: {;
      extractTex.t?: boolea.n;
      generateSummar.y?: boolea.n;
      extractEntitie.s?: boolea.n;
      generateEmbedding.s?: boolea.n;
      classifyConten.t?: boolea.n;
};
  ): Promis.e<unknow.n> {;
    tr.y {;
      // Ad.d t.o processin.g queu.e;
      cons.t jobI.d = awai.t thi.s.addToQueu.e({;
        queu.e: thi.s.aiProcessingQueu.e;
        jobTyp.e: 'full_file_processin.g';
        payloa.d: {;
          fileI.d;
          option.s: {;
            extractTex.t: tru.e;
            generateSummar.y: tru.e;
            extractEntitie.s: tru.e;
            generateEmbedding.s: tru.e;
            classifyConten.t: tru.e;
            ...option.s}};
        priorit.y: 3});
      // Subscrib.e t.o jo.b update.s;
      retur.n ne.w Promis.e((resolv.e, rejec.t) => {;
        cons.t unsubscrib.e = thi.s.subscribeToDatabaseChange.s(;
          'job_queu.e';
          (payloa.d) => {;
            i.f (payloa.d.ne.w?.i.d === jobI.d) {;
              i.f (payloa.d.ne.w.statu.s === 'complete.d') {;
                unsubscrib.e();
                resolv.e(payloa.d.ne.w.resul.t)} els.e i.f (payloa.d.ne.w.statu.s === 'faile.d') {;
                unsubscrib.e();
                rejec.t(ne.w Erro.r(payloa.d.ne.w.error_messag.e))};
            };
          };
          { i.d: `e.q.${jobI.d}` };
        );
      });
    } catc.h (erro.r) {;
      logge.r.erro.r('Faile.d t.o proces.s fil.e wit.h A.I pipelin.e:', LogContex.t.A.I, { erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r));
      thro.w erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r)};
  };

  // =====================================================;
  // HELPE.R METHOD.S;
  // =====================================================;

  privat.e asyn.c generateFileHas.h(fil.e: Buffe.r | Blo.b | Fil.e): Promis.e<strin.g> {;
    cons.t buffe.r = fil.e instanceo.f Buffe.r ? fil.e : Buffe.r.fro.m(awai.t (fil.e a.s Blo.b).arrayBuffe.r());
    retur.n createHas.h('sh.a256').updat.e(buffe.r).diges.t('he.x')};

  privat.e asyn.c findFileByHas.h(bucke.t: strin.g, has.h: strin.g): Promis.e<unknow.n> {;
    cons.t { dat.a } = awai.t thi.s.clien.t;
      .fro.m('file_metadat.a');
      .selec.t('*');
      .e.q('bucke.t', bucke.t);
      .e.q('has.h', has.h);
      .singl.e();
    retur.n dat.a;
  };

  privat.e asyn.c saveFileMetadat.a(metadat.a: an.y): Promis.e<unknow.n> {;
    cons.t { dat.a, erro.r } = awai.t thi.s.clien.t;
      .fro.m('file_metadat.a');
      .inser.t(metadat.a);
      .selec.t();
      .singl.e();
    i.f (erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r) thro.w erro.r instanceo.f Erro.r ? erro.r.messag.e : Strin.g(erro.r);
    retur.n dat.a;
  };

  privat.e asyn.c triggerFileProcessin.g(fileI.d: strin.g): Promis.e<voi.d> {;
    awai.t thi.s.callEdgeFunctio.n({;
      functionNam.e: 'trigge.r-fil.e-processin.g';
      payloa.d: { fileI.d }});
  };

  /**;
   * Cleanu.p resource.s;
   */;
  publi.c cleanu.p(): voi.d {;
    // Unsubscrib.e fro.m al.l realtim.e channel.s;
    thi.s.realtimeChannel.s.forEac.h((channe.l) => {;
      channe.l.unsubscrib.e()});
    thi.s.realtimeChannel.s.clea.r();
  };
};

// Expor.t singleto.n instanc.e;
expor.t cons.t enhancedSupabas.e = EnhancedSupabaseServic.e.getInstanc.e();