# Prometheus Configuration for Distributed Tracing
# Collects metrics from OpenTelemetry services

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'universal-ai-tools'
    environment: 'tracing'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Rules configuration
rule_files:
  - "alert_rules.yml"

# Scrape configurations
scrape_configs:
  # Core tracing infrastructure (operational)
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']
    metrics_path: /metrics

  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
    metrics_path: /metrics

  # Future application services (commented out until deployed)
  # - job_name: 'universal-ai-services'
  #   static_configs:
  #     - targets:
  #         - 'llm-router:9001'      # Rust LLM Router
  #         - 'agent-registry:9002'  # Rust Agent Registry
  #         - 'websocket-service:9003' # Go WebSocket Service
  #         - 'analytics-service:9004' # Rust Analytics Service
  #   metrics_path: /metrics
  #   scrape_interval: 15s

  # - job_name: 'intelligent-load-balancer'
  #   static_configs:
  #     - targets: ['intelligent-load-balancer:9090']
  #   metrics_path: /metrics

  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']
  #   metrics_path: /metrics

  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
  #   metrics_path: /metrics

# Remote write configuration for metric correlation
remote_write:
  - url: http://tempo:3200/api/v1/push
    headers:
      X-Scope-OrgID: "universal-ai-tools"