# Prometheus scrape config for TRM Router metrics
# Add to prometheus.yml under scrape_configs

- job_name: 'trm-router'
  scrape_interval: 15s
  scrape_timeout: 10s
  static_configs:
    - targets:
        - '127.0.0.1:8014'  # athena-evolutionary
        - '127.0.0.1:8888'  # athena-api
  metrics_path: '/metrics'
  scheme: 'http'

- job_name: 'routing-outcomes'
  scrape_interval: 30s
  static_configs:
    - targets:
        - '127.0.0.1:8014'
  metrics_path: '/metrics'
  metric_relabel_configs:
    # Only keep routing-related metrics
    - source_labels: [__name__]
      regex: 'routing_.*|trm_.*|model_.*|rag_.*'
      action: keep

