[package]
name = "tech-scanner"
version = "0.1.0"
edition = "2021"
authors = ["Universal AI Tools Team"]
description = "Technology detection and monitoring service for self-evolving architecture"

[dependencies]
# Core async runtime
tokio = { version = "1.37", features = ["full"] }

# HTTP server and client
axum = { version = "0.7", features = ["macros"] }
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["cors", "trace"] }

# Serialization and data structures
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.8", features = ["v4", "serde"] }

# Database
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "chrono", "uuid"] }

# Logging and tracing
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# OpenTelemetry distributed tracing
opentelemetry = "0.22"
opentelemetry_sdk = { version = "0.22", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.15", features = ["grpc-tonic"] }
tracing-opentelemetry = "0.23"

# Metrics
prometheus = "0.13"

# Time handling
chrono = { version = "0.4", features = ["serde"] }

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Configuration
config = "0.14"

# Async utilities
tokio-cron-scheduler = "0.10"
futures = "0.3"

# Web scraping and parsing
scraper = "0.19"
url = "2.5"

# Hashing and comparison
blake3 = "1.5"

# GitHub API integration
octocrab = "0.38"

# RSS/Atom feed parsing
feed-rs = "1.3"

# Regex for pattern matching
regex = "1.10"

# TOML parsing
toml = "0.8"

# Async recursion
async-recursion = "1.1"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true