global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'universal-ai-tools'
    environment: 'production'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Universal AI Tools Main Application
  - job_name: 'universal-ai-tools'
    static_configs:
      - targets: ['universal-ai-tools:9999']
    metrics_path: '/metrics'
    scrape_interval: 15s
    relabel_configs:
      - target_label: service
        replacement: 'universal-ai-tools'
      - target_label: language
        replacement: 'nodejs'

  # Health endpoint monitoring
  - job_name: 'universal-ai-health'
    static_configs:
      - targets: ['universal-ai-tools:9999']
    metrics_path: '/api/health'
    scrape_interval: 30s
    relabel_configs:
      - target_label: service
        replacement: 'universal-ai-health'

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    relabel_configs:
      - target_label: service
        replacement: 'redis'

  # Supabase Database
  - job_name: 'supabase'
    static_configs:
      - targets: ['supabase:54321']
    scrape_interval: 30s
    relabel_configs:
      - target_label: service
        replacement: 'supabase'

  # Ollama Local LLM
  - job_name: 'ollama'
    static_configs:
      - targets: ['ollama:11434']
    metrics_path: '/api/tags'
    scrape_interval: 60s
    relabel_configs:
      - target_label: service
        replacement: 'ollama'

  # Container metrics via node exporter (if available)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Docker container metrics via cAdvisor (if available)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s