template_id = "rust_service"
name = "Rust Microservice"
description = "A high-performance Rust microservice with Axum web framework"
language = "rust"
framework = "axum"
dependencies = [
    "tokio",
    "axum",
    "serde",
]

[[files]]
source_path = "Cargo.toml.hbs"
target_path = "Cargo.toml"
is_template = true
executable = false

[[files]]
source_path = "src/main.rs.hbs"
target_path = "src/main.rs"
is_template = true
executable = false

[[files]]
source_path = "src/config.rs.hbs"
target_path = "src/config.rs"
is_template = true
executable = false

[[parameters]]
name = "service_name"
parameter_type = "string"
description = "Name of the service"
default_value = "my_service"
required = true
validation = "^[a-z][a-z0-9_]*$"

[[parameters]]
name = "port"
parameter_type = "number"
description = "Port number for the service"
default_value = 8080
required = false

[[post_generation_steps]]
step_type = "command"
description = "Format code with rustfmt"
command = "cargo fmt"

[post_generation_steps.parameters]
