apiVersion: apps/v1
kind: Deployment
metadata:
  name: universal-ai-tools
  namespace: ai-tools
  labels:
    app: universal-ai-tools
    version: rust-v1
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: universal-ai-tools
  template:
    metadata:
      labels:
        app: universal-ai-tools
        version: rust-v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9999"
        prometheus.io/path: "/api/v1/monitoring/metrics"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - universal-ai-tools
              topologyKey: kubernetes.io/hostname
      containers:
      - name: app
        image: universal-ai-tools:rust-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9999
          name: http
          protocol: TCP
        - containerPort: 8080
          name: websocket
          protocol: TCP
        env:
        - name: NODE_ENV
          value: production
        - name: PORT
          value: "9999"
        - name: ENABLE_RUST_SERVICES
          value: "true"
        - name: RUST_LOG
          value: info
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: ai-tools-secrets
              key: database-url
        - name: REDIS_URL
          value: redis://redis-service:6379
        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: ai-tools-secrets
              key: supabase-url
        - name: SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: ai-tools-secrets
              key: supabase-anon-key
        - name: SUPABASE_SERVICE_KEY
          valueFrom:
            secretKeyRef:
              name: ai-tools-secrets
              key: supabase-service-key
        - name: OLLAMA_URL
          value: http://ollama-service:11434
        - name: NODE_OPTIONS
          value: "--max-old-space-size=4096"
        - name: UV_THREADPOOL_SIZE
          value: "128"
        resources:
          requests:
            cpu: 2000m
            memory: 4Gi
          limits:
            cpu: 4000m
            memory: 8Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 9999
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 9999
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: app-data
          mountPath: /app/data
        - name: app-cache
          mountPath: /app/cache
        - name: mlx-models
          mountPath: /app/models
      volumes:
      - name: app-data
        persistentVolumeClaim:
          claimName: app-data-pvc
      - name: app-cache
        emptyDir:
          sizeLimit: 2Gi
      - name: mlx-models
        persistentVolumeClaim:
          claimName: mlx-models-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: universal-ai-tools-service
  namespace: ai-tools
  labels:
    app: universal-ai-tools
spec:
  type: LoadBalancer
  selector:
    app: universal-ai-tools
  ports:
  - name: http
    port: 80
    targetPort: 9999
    protocol: TCP
  - name: websocket
    port: 8080
    targetPort: 8080
    protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: universal-ai-tools-hpa
  namespace: ai-tools
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: universal-ai-tools
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 1
        periodSeconds: 60
      selectPolicy: Min
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-data-pvc
  namespace: ai-tools
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: fast-ssd
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlx-models-pvc
  namespace: ai-tools
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: fast-ssd
  resources:
    requests:
      storage: 500Gi