metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

# System module
metricbeat.modules:
  # System metrics
  - module: system
    metricsets:
      - cpu
      - load
      - memory
      - network
      - process
      - process_summary
      - socket_summary
      - filesystem
      - fsstat
    enabled: true
    period: 10s
    processes: ['.*']
    process.include_top_n:
      by_cpu: 5
      by_memory: 5

  # Docker metrics
  - module: docker
    metricsets:
      - container
      - cpu
      - diskio
      - healthcheck
      - info
      - memory
      - network
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s
    enabled: true

  # Elasticsearch metrics (if monitoring Elasticsearch)
  - module: elasticsearch
    metricsets:
      - node
      - node_stats
    period: 10s
    hosts: ["http://elasticsearch:9200"]
    enabled: true

# Output to Elasticsearch
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  indices:
    - index: "metricbeat-%{+yyyy.MM.dd}"

# Kibana endpoint
setup.kibana:
  host: "kibana:5601"

# Dashboards
setup.dashboards.enabled: true

# Logging
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/metricbeat
  name: metricbeat
  keepfiles: 7
  permissions: 0644

# Processors
processors:
  - add_host_metadata: ~
  - add_docker_metadata: ~
  - add_cloud_metadata: ~

