[package]
name = "reveal-evolution-service"
version = "0.1.0"
edition = "2021"
authors = ["Universal AI Tools Team"]
description = "High-performance ReVeal-based evolution engine with iterative generation-verification"

[dependencies]
# Core async runtime
tokio = { version = "1.40", features = ["full"] }
async-trait = "0.1"

# HTTP Server
actix-web = "4.9"
actix-cors = "0.7"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rmp-serde = "1.3"  # MessagePack for FFI

# Data structures
dashmap = "6.1"
nalgebra = "0.33"
uuid = { version = "1.11", features = ["v4", "serde"] }

# Machine Learning
ndarray = "0.16"
smartcore = "0.3"  # For Bayesian models

# Parallel processing
rayon = "1.10"
crossbeam = "0.8"

# Caching and persistence
redis = { version = "0.27", features = ["tokio-comp", "connection-manager"] }

# Metrics and logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
prometheus = { version = "0.13", features = ["process"] }

# Error handling
thiserror = "2.0"
anyhow = "1.0"

# FFI for Node.js integration
neon = { version = "1.0", optional = true }

# Internal dependencies - temporarily disabled for standalone compilation
# ab-mcts-service = { path = "../ab-mcts-service" }
# intelligent-parameter-service = { path = "../intelligent-parameter-service" }

# Random number generation
rand = "0.8"
rand_distr = "0.4"

# Time utilities
instant = "0.1"
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
criterion = "0.5"
proptest = "1.6"
tokio-test = "0.4"
wiremock = "0.6"

[features]
default = ["ffi"]
ffi = ["neon"]
benchmark = []

# [[bench]]
# name = "evolution_bench"
# harness = false

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true

[profile.bench]
inherits = "release"
debug = true