name: NeuroForgeApp
options:
  minimumXcodeGenVersion: 2.38.0
  deploymentTarget:
    macOS: "13.0"

settings:
  base:
    SWIFT_VERSION: 5.10

targets:
  NeuroForgeApp:
    type: application
    platform: macOS
    sources:
      - path: Sources/NeuroForgeApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.universalaitools.mac
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_ALLOWED: NO
        GENERATE_INFOPLIST_FILE: YES
    scheme:
      testTargets:
        - name: NeuroForgeAppUITests
          parallelizable: true
      environmentVariables:
        API_BASE: http://localhost:8014
        QA_MODE: "1"

  NeuroForgeAppUITests:
    type: bundle.ui-testing
    platform: macOS
    sources:
      - path: UITests
    dependencies:
      - target: NeuroForgeApp
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGN_IDENTITY: "-"
        INFOPLIST_KEY_CFBundleName: NeuroForgeAppUITests
