[package]
name = "architecture-ai"
version = "0.1.0"
edition = "2021"
authors = ["Universal AI Tools Team"]
description = "AI-driven architecture decision engine for autonomous system evolution"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
axum = "0.7"
tower = "0.4"
tower-http = { version = "0.5", features = ["cors"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1.0", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "chrono", "uuid"] }
reqwest = { version = "0.11", features = ["json"] }
toml = "0.8"
regex = "1.0"
async-recursion = "1.0"

# AI/ML libraries for decision making - updated to latest versions
candle-core = "0.9"
candle-nn = "0.9"
candle-transformers = "0.9"

# Code generation and templating
handlebars = "4.0"
walkdir = "2.0"

# Metrics and observability
prometheus = "0.13"
opentelemetry = "0.21"
opentelemetry_sdk = "0.21"
opentelemetry-prometheus = "0.14"

[dev-dependencies]
tokio-test = "0.4"

[[bin]]
name = "architecture-ai"
path = "src/main.rs"