[package]
name = "performance-optimizer"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "performance-optimizer"
path = "src/main.rs"

[dependencies]
# Web framework
axum = { version = "0.7", features = ["json", "tower-log"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["cors", "trace"] }
tokio = { version = "1.0", features = ["full"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# HTTP client for service communication
reqwest = { version = "0.11", features = ["json"] }

# Logging and tracing
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Async utilities
futures = "0.3"
uuid = { version = "1.0", features = ["v4"] }

# System monitoring and metrics
sysinfo = "0.30"
psutil = "3.2"

# Time utilities
chrono = { version = "0.4", features = ["serde"] }

# Configuration
config = "0.14"

# Metrics and monitoring
prometheus = { version = "0.13", features = ["process"] }

# Database connections
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "chrono", "uuid"] }
redis = { version = "0.24", features = ["tokio-comp", "connection-manager"] }

# Performance profiling
pprof = { version = "0.12", features = ["flamegraph", "protobuf-codec"] }

# Mathematical computations
nalgebra = "0.32"
statrs = "0.16"