apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-router
  namespace: universal-ai-tools
  labels:
    app: llm-router
    tier: backend
    component: ai-routing
    version: v1.0.0
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: llm-router
  template:
    metadata:
      labels:
        app: llm-router
        tier: backend
        component: ai-routing
        version: v1.0.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9001"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: llm-router
        image: universal-ai-tools/llm-router:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
          name: http
          protocol: TCP
        - containerPort: 9001
          name: metrics
          protocol: TCP
        env:
        - name: RUST_LOG
          value: "info"
        - name: SERVICE_NAME
          value: "llm-router"
        - name: LLM_ROUTER_HOST
          value: "0.0.0.0"
        - name: LLM_ROUTER_PORT
          value: "8001"
        - name: METRICS_PORT
          value: "9001"
        - name: LLM_ROUTER_WORKERS
          value: "4"
        - name: LLM_ROUTER_MAX_CONNECTIONS
          value: "1000"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: database-url
        - name: REDIS_URL
          value: "redis://redis:6379"
        - name: OTEL_SERVICE_NAME
          value: "llm-router"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector:4317"
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 20
          periodSeconds: 30
          timeoutSeconds: 15
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: llm-router
  namespace: universal-ai-tools
  labels:
    app: llm-router
    tier: backend
    component: ai-routing
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9001"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8001
    targetPort: 8001
    protocol: TCP
  - name: metrics
    port: 9001
    targetPort: 9001
    protocol: TCP
  selector:
    app: llm-router
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: llm-router-pdb
  namespace: universal-ai-tools
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: llm-router
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: llm-router-hpa
  namespace: universal-ai-tools
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: llm-router
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60