[package]
name = "ffi-bridge"
version = "0.1.0"
edition = "2021"
authors = ["Universal AI Tools Team"]
description = "FFI bridge for direct Rust-Go communication"

[lib]
crate-type = ["cdylib", "staticlib"]
name = "rust_go_bridge"

[dependencies]
# Core
libc = "0.2"
once_cell = "1.19"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"
rmp-serde = "1.1"  # MessagePack for efficient binary serialization

# Async runtime
tokio = { version = "1.35", features = ["full"] }
futures = "0.3"

# Shared memory
shared_memory = "0.12"
memmap2 = "0.9"

# Zero-copy serialization
flatbuffers = "23.5"
capnp = "0.18"

# Error handling
thiserror = "1.0"
anyhow = "1.0"

# Logging
tracing = "0.1"
tracing-subscriber = "0.3"

# Thread safety
crossbeam = "0.8"
parking_lot = "0.12"
dashmap = "5.5"

[build-dependencies]
cbindgen = "0.26"

[features]
default = ["msgpack"]
msgpack = []
flatbuf = []
capnproto = []