name: Smoke Test
on: [push, pull_request]

jobs:
  sentry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install httpx fastapi uvicorn[standard]
      
      - name: Start API server
        run: |
          PYTHONPATH=$PWD/src:$PWD/api:$PWD uvicorn api.app:app --host 0.0.0.0 --port 8013 &
          echo $! > /tmp/api_server.pid
          sleep 5
      
      - name: Run error sentry (fail on 500s)
        run: BASE=http://localhost:8013 python scripts/error_sentry.py
      
      - name: Stop server
        if: always()
        run: |
          if [ -f /tmp/api_server.pid ]; then
            kill $(cat /tmp/api_server.pid) || true
            rm /tmp/api_server.pid
          fi

