name: Syntax Check

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  syntax-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check for common syntax errors
        run: |
          echo "🔍 Checking for common syntax errors..."
          if grep -r -E "(_error\s|_errorinstanceof|error:|_content|requestincludes|pattern\s/)" --include="*.ts" --include="*.tsx" src/; then
            echo "❌ Found syntax errors that must be fixed"
            exit 1
          else
            echo "✅ No common syntax errors found"
          fi

      - name: Run TypeScript compiler
        run: npm run type-check

      - name: Run ESLint
        run: npm run lint

      - name: Check code formatting
        run: npm run format:check

      - name: Generate syntax report
        if: failure()
        run: |
          npm run syntax:report || true
          if [ -f SYNTAX_REPORT.md ]; then
            cat SYNTAX_REPORT.md
          fi

      - name: Upload syntax report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: syntax-report-${{ matrix.node-version }}
          path: SYNTAX_REPORT.md
          retention-days: 7
