/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface VoiceProcessingConfig {
  sampleRate: number
  channels: number
  chunkSize: number
  whisperModel: string
  ttsModel: string
  enableVad: boolean
  enableNoiseReduction: boolean
}
export interface AudioChunk {
  data: Buffer
  timestamp: number
  duration: number
  sampleRate: number
  channels: number
}
export interface SpeechResult {
  text: string
  confidence: number
  language: string
  processingTimeMs: number
}
export interface SynthesisResult {
  audioData: Buffer
  duration: number
  sampleRate: number
  processingTimeMs: number
}
export interface ProcessingMetrics {
  totalChunksProcessed: number
  averageProcessingTimeMs: number
  peakProcessingTimeMs: number
  totalAudioDurationSeconds: number
  realTimeFactor: number
}
export declare function processAudioFileSync(filePath: string, config?: VoiceProcessingConfig | undefined | null): SpeechResult
export declare function validateAudioChunk(audioChunk: AudioChunk): boolean
export declare function getVersion(): string
export declare function benchmarkProcessing(chunkCount: number): string
export declare class VoiceProcessor {
  constructor(config?: VoiceProcessingConfig | undefined | null)
  initialize(): string
  createSession(sessionId: string, userId?: string | undefined | null): string
  processAudioChunk(sessionId: string, audioChunk: AudioChunk): SpeechResult | null
  synthesizeSpeech(sessionId: string, text: string, voice?: string | undefined | null): SynthesisResult
  getSessionStats(sessionId: string): string | null
  cleanupSession(sessionId: string): void
  getPerformanceMetrics(): ProcessingMetrics
  getConfig(): VoiceProcessingConfig
  getSessionCount(): number
}
